CREATE TABLE payment_instruction (
  instruction_id              VARCHAR(64) PRIMARY KEY,
  source_system               VARCHAR(64) NOT NULL,
  payer_account               VARCHAR(64) NOT NULL,
  payee_account               VARCHAR(64) NOT NULL,
  amount                      DECIMAL(19, 4) NOT NULL,
  currency                    VARCHAR(3) NOT NULL,
  requested_execution_date    DATE NOT NULL,
  status                      VARCHAR(32) NOT NULL,
  failure_reason              VARCHAR(255),
  created_at                  TIMESTAMP NOT NULL,
  updated_at                  TIMESTAMP NOT NULL
);

CREATE INDEX idx_pi_status_updated ON payment_instruction(status, updated_at);

CREATE TABLE payment_instruction_event (
  event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instruction_id  VARCHAR(64) NOT NULL,
  event_type      VARCHAR(64) NOT NULL,
  old_status      VARCHAR(32),
  new_status      VARCHAR(32),
  event_time      TIMESTAMP NOT NULL,
  details         VARCHAR(1000),
  CONSTRAINT fk_pi_event_instruction
    FOREIGN KEY (instruction_id) REFERENCES payment_instruction(instruction_id)
);
